"""Centralized default configuration values for IDICOC core.

Keep thresholds and global constants here to avoid scattering magic numbers
across the codebase.
"""

DEFAULT_DISSONANCE_WEIGHTS = (
    0.0,  # λ0
    0.5,  # λ1
    0.4,  # λ2
    0.1,  # λ3
    0.0,  # λ4
    0.0,  # λ5
    0.0,  # λ6
)

DEFAULT_SEMANTIC_EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
DEFAULT_SEMANTIC_NLI_MODEL = "facebook/bart-large-mnli"
DEFAULT_SEMANTIC_NLI_CONFLICT_THRESHOLD = 0.5
DEFAULT_SEMANTIC_NLI_WARNING_THRESHOLD = 0.75
DEFAULT_SEMANTIC_MIN_RAG_SCORE = 0.1
DEFAULT_TERMINAL_RIGIDITY_THRESHOLD = 0.01
DEFAULT_EMBEDDING_MAX_CHUNKS = 10


__all__ = [
    "DEFAULT_DISSONANCE_WEIGHTS",
    "DEFAULT_SEMANTIC_EMBEDDING_MODEL",
    "DEFAULT_SEMANTIC_NLI_MODEL",
    "DEFAULT_SEMANTIC_NLI_CONFLICT_THRESHOLD",
    "DEFAULT_SEMANTIC_NLI_WARNING_THRESHOLD",
    "DEFAULT_SEMANTIC_MIN_RAG_SCORE",
    "DEFAULT_TERMINAL_RIGIDITY_THRESHOLD",
    "DEFAULT_EMBEDDING_MAX_CHUNKS",
]
