from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional

class AEMStorageBackend(ABC):
    @abstractmethod
    def save_entropy_event(self, event: Dict[str, Any]) -> None: ...
    @abstractmethod
    def load_all_events(self) -> Dict[str, List[Dict[str, Any]]]: ...
    @abstractmethod
    def clear(self) -> None: ...

class CTMStorageBackend(ABC):
    @abstractmethod
    def save_node(self, node_hash: str, node_data: Dict[str, Any]) -> None: ...
    @abstractmethod
    def load_node(self, node_hash: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    def load_all_nodes(self) -> Dict[str, Dict[str, Any]]: ...
    @abstractmethod
    def save_root_hash(self, root_hash: str) -> None: ...
    @abstractmethod
    def load_root_hash(self) -> Optional[str]: ...
